version: "3"
services:
  web:
    # username/repo:tag を皆さんの名前とイメージに置き換えます
    image: tetsunog/get-staeted:v0.1
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
